# Generated by Django 4.0.4 on 2024-11-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
