# Generated by Django 5.1.3 on 2024-11-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagnestapp', '0002_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
